pkg/builder/builder.go
Remove error when evaluating cpackget location since its presence is not mandatory.
Issue [#2](https://github.com/Open-CMSIS-Pack/cbuild/issues/2)
=> Remove error when evaluating cpackget location

.github/workflows/test.yml, .golangci.yml, cmd/cbuild/root.go, pkg/builder/builder.go, pkg/builder/builder_test.go
- Fixes the second issue described in https://github.com/Open-CMSIS-Pack/devtools/issues/374
- Introduces the `--packs` option for enabling the download of missing packs with cpackget
- Introduces the `--rebuild` option (clean + build) which seems to be the expectation in https://github.com/Open-CMSIS-Pack/cbuild/issues/5.
=> Add --rebuild and --packs options

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
The change includes:
- Go version updated to 1.19.3
- Added vulnerability check
- Added concurrency options (This should stop the obsolete and redundant jobs from the same parent and save computational hours)
=> Updated go version to 1.19.3 and added vulnerability check

.github/workflows/test.yml
In case of failure, there was no way for the user to check about the detected vulnerabilities. With these results printing, the user can see in the workflow the reason of the failures and address them.
=> Show vulnerability check results

pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This change addresses the following:
- [Issue-46](https://github.com/Open-CMSIS-Pack/cbuild/issues/46)
- Code cleanup and restructuring
- stdout string changes
- Changed `Building context` to `Processing context`
- Moved line separator (======) above context info  
```
==================================================
info cbuild: Processing context: "Hello.Debug+AVH"
```
=> Fix: cbuild throws error with project having no buildType

cmd/cbuild/commands/list/list.go, cmd/cbuild/commands/list/list_environment.go, cmd/cbuild/commands/list/list_environment_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/utils/configs.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Related to https://github.com/Open-CMSIS-Pack/devtools/issues/783
Extended `cbuild` with `list environment` command
for e.g
```
$ cbuild list environment
CMSIS_PACK_ROOT=C:/Users/Test/AppData/Local/Arm/Packs
CMSIS_COMPILER_ROOT=C:/Test/cmsis-toolbox/etc
cmake=C:/tools/bin/cmake.exe, version 3.26.0
ninja=C:/Users/Test/AppData/Local/Programs/Python/Python310/Scripts/ninja.exe, version 1.10.2
```
or 
```
$ cbuild list environment
CMSIS_PACK_ROOT=C:/Users/Test/AppData/Local/Arm/Packs
CMSIS_COMPILER_ROOT=C:/Test/cmsis-toolbox/etc
cmake=<Not Found>
ninja=<Not Found>
```
or
```
$ cbuild list environment -h
Print list of environment configurations
Usage:
cbuild list environment [flags]
Flags:
-h, --help   help for environment
Global Flags:
-l, --log string   Save output messages in a log file
```
=> [cbuild] Add list environment command

pkg/builder/cproject/builder.go, pkg/builder/cproject/builder_test.go
The change includes
- Printing `CMake `and `cbuildgen `commands in `--debug` mode. The commands should be listed as 
- `debug cbuild: cbuildgen command: <COMMAND>`
- `debug cbuild: cmake configuration command: <COMMAND>`
- `debug cbuild: cmake build command: <COMMAND>`
- Checks the existence of `CMakelists.txt` file before running `cmake `commands
=> Print commands in debug mode

cmd/cbuild/commands/build/buildcprj_test.go, cmd/cbuild/commands/list/list_contexts_test.go, cmd/cbuild/commands/list/list_test.go, cmd/cbuild/commands/list/list_toolchains_test.go, cmd/cbuild/commands/root_test.go, pkg/builder/cproject/builder_test.go, pkg/builder/csolution/builder_test.go, pkg/inittest/inittest.go, pkg/utils/configs.go, pkg/utils/configs_test.go, pkg/utils/utils.go
Addressing issue : https://github.com/Open-CMSIS-Pack/cbuild/issues/73
=> Remove $CMSIS_BUILD_ROOT references and test structure cleanup

cmd/cbuild/commands/build/buildcprj_test.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/root_test.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1042
- If the path doesn't exist, create a log file path
- Throws an error, when unable to create a directory or file
- Stop the execution in case of an error
=> Create log file parent path

.github/workflows/release.yml, .github/workflows/tpip-check.yml, scripts/template/third_party_licenses.md.template
Run TPIP workflow nightly. It will create a PR only when it finds a change in the packages used.
Also for simplicity of the solution, we have removed the timestamp from the report.
=> Updated TPIP schedule

.codeclimate.yml, README.md
Added badges and code climate configuration file.
Please note that currently only the identical and similar code scans are enabled. All style checks are disabled for the time being.
=> CodeClimate configs

.github/workflows/global.yaml, .pre-commit-config.yaml, scripts/check_copyright_notice.py
Added copyright checker to iterate through each go file and check if the copyright notice is declared.
=> Copyright checker

cmd/cbuild/commands/root.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go
Addressing: https://github.com/Open-CMSIS-Pack/cbuild/issues/97
=> Added -S,--context-set option

cmd/cbuild/commands/root.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go, pkg/utils/utils.go, pkg/utils/utils_test.go
addressing: https://github.com/Open-CMSIS-Pack/cbuild/issues/114
=> Fix: Build only selected contexts

pkg/utils/utils.go, pkg/utils/utils_test.go
Addressing and replicating: https://github.com/Arm-Debug/devtools-external/pull/740#issue-2008502492
=> [cbuild] Improved context filtering

.github/workflows/release.yml
- Adapting workflow because the new version of download-artifact action has [breaking changes](https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes).
- `--rm-dist` has been deprecated in favor of `--clean` [link](https://goreleaser.com/deprecations/#__tabbed_11_2)
- Added `pull_request `event to ensure operational workflow
=> Adapt workflow for new download-artifact action changes

cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, cmd/cbuild/commands/setup/setup_test.go, pkg/builder/cproject/builder.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go
Addressing partially https://github.com/Open-CMSIS-Pack/devtools/issues/1322
```
cbuild: Build Invocation test (C) 2024 Arm Ltd. and Contributors
Usage:
cbuild [command] <name>.csolution.yml [options]
Commands:
buildcprj   Use a *.CPRJ file as build input
help        Help about any command
list        List information about environment, toolchains, and contexts
setup       Initialize project
```
```
$ cbuild setup -h
Initialize project
Usage:
cbuild setup <name>.csolution.yml [options]
Options:
--cbuild2cmake       Use cbuild2cmake
-C, --clean              Remove intermediate and output directories
-c, --context arg [...]  Input context names [<project-name>][.<build-type>][+<target-type>]
-S, --context-set        Use context set
-d, --debug              Enable debug messages …
```
=> Extend command line with setup command

pkg/builder/csolution/builder.go
This update comprises 3 enhancements:
- Restricting the `list layers` call to only processed contexts.
- Stop generation of the` commands.json` database upon encountering errors in locating layer variable definitions
- Continue with file generation upon setup command even when required packs are missing
=> setup command improvements

pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/interface.go
Avoid replacing command line options `b.Options.Contexts`
Improve `--target` option handling, enabling additional cmake targets - related to https://github.com/Open-CMSIS-Pack/cbuild2cmake/issues/87
=> Improve cmake `--target` option handling for `cbuild2cmake`

pkg/builder/csolution/builder.go, pkg/utils/utils.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1293
At the moment, it's not feasible to separate build logs for different projects in cbuild2cmake. Therefore, the change addresses only the overarching build summary message, indicating: 
- `Build summary: Build completed successfully - Time Elapsed: 00:00:16`
- `Build summary: Build failed - Time Elapsed: 00:00:11`
=> Added build summary message

.github/workflows/test.yml, .golangci.yml
level=error msg="[linters_context] `structcheck`: This linter is fully inactivated: it will not produce any reports."
level=error msg="[linters_context] `varcheck`: This linter is fully inactivated: it will not produce any reports."
level=error msg="[linters_context] `deadcode`: This linter is fully inactivated: it will not produce any reports."
=> Removed Inactivated linters from lint jobs

pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/builder/cproject/builder.go, pkg/builder/csolution/builder.go, pkg/builder/interface.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This update includes the following changes:
- Invoked `cbuild2cmake` for each context.
- Added a build summary message.
- Changed the build log separator from "=" to "-"
- Cleanup cbuild errors, these errors should come from the utility triggered
```
+----------------------------------------
(1/2) Building context: "Hello.Debug+AVH"
info cbuild2cmake: Generate CMakeLists 0.9.2-devint1 (C) 2024 Arm Ltd. and Contributors
info cbuild2cmake: CMakeLists were successfully generated in the C:/Sandbox/opensource/csolution-examples/Hello/tmp directory
[1/9] Creating directories for 'Hello.Debug+AVH'
[2/9] No download step for 'Hello.Debug+AVH'
[3/9] No update step for 'Hello.Debug+AVH'
[4/9] No patch step for 'Hello.Debug+AVH'
[5/9] Performing configure step for 'Hello.Debug+AVH'
-- The C compiler …
```
=> Run cbuild2cmake per context

pkg/builder/cbuildidx/builder.go, pkg/builder/csolution/builder.go
Aligned with https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/135 improvements
=> [cbuild] Reduce default verbosity when using `cbuild2cmake` mode

pkg/builder/cbuildidx/builder.go
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1563
=> [cbuild] Fix `setup` command in `cbuild2cmake` mode to use only `<context>-database` targets

.github/workflows/test.yml, cmd/cbuild/commands/build/buildcprj.go, cmd/cbuild/commands/build/buildcprj_test.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/root_test.go, cmd/cbuild/commands/setup/setup.go, cmd/cbuild/main.go, pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/builder/cproject/builder.go, pkg/builder/cproject/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go, pkg/errutils/errutils.go, pkg/errutils/errutils_test.go, pkg/utils/configs.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/data/TestSolution/test.cbuild-idx.yml, test/data/TestSolution/test.cbuild-set.yml
This update includes the following changes:
1. To reduce log noise, the default log mode is set to Warn+, which means only warning and error messages will be logged by default.
2. Error messages have been revised to be more intuitive for users.
3. Redundant error messages have been removed.
4. Removed `error cbuild: exit status 1`
5. `.csolution.yml` is now the expected extension and `.csolution.yaml` is no longer accepted
Note: Please be informed that to get the detailed logs use `--verbose` option
=> Set default log mode to Warn+ and streamline error handling and cleanup

cmd/cbuild/commands/root.go
Removing default keyword to appear twice
`--cbuild2cmake       Use build information files with cbuild2cmake backend (default) (default true)`
=> Duplicate default keyword in usage

pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/utils/utils.go, test/data/Test.cbuild-idx.yml
Fix regression reported in https://github.com/Open-CMSIS-Pack/cbuild/issues/244
If no `--context` is specified, run cmake build target `all` to trigger `executes` steps
=> [cbuild] Improve CMake `--target` handling in `cbuild2cmake` mode

cmd/cbuild/commands/setup/setup.go, cmd/cbuild/main.go, pkg/errutils/errutils.go
The change includes:
- Making of `-S, --context-set` argument as mandatory for setup command
- cbuild returning only error code `1` & `0` for fail and successful respectively
- Setting a default value for --jobs to 8
=> Make -S,--context-set as mandatory arg for setup command

pkg/builder/csolution/builder.go
Fixed the crash when using `cbuild setup ./test.csolution.yml -S` when the project has schema issues. for e.g. target types are missing etc
Moved the `listcontexts` call to the beginning so that any errors with the schema are reported first.
=> Fixed crash with setup command

pkg/builder/cbuildidx/builder.go, pkg/utils/utils.go, test/data/Test.cbuild-idx.yml
Address `cbuild` part of https://github.com/Open-CMSIS-Pack/devtools/issues/1607
=> [cbuild] Add `tmpdir` node handling for solution level temporary files

pkg/builder/csolution/builder.go, pkg/utils/utils.go, pkg/utils/utils_test.go
aligning with : https://github.com/Open-CMSIS-Pack/devtools/issues/1562
=> Align selection of first build & target type when cbuild-set doesn't exist

pkg/builder/cbuildidx/builder.go
Complementary to https://github.com/Open-CMSIS-Pack/cbuild/pull/262
=> [cbuild] Fix custom `tmpdir` retrieval

pkg/builder/csolution/builder.go, pkg/utils/utils.go, pkg/utils/utils_test.go
This change addresses the cleanup of the patch fix that was initially introduced to accommodate cpackget's limitation of not handling '>='. Since cpackget now supports [this functionality](https://github.com/Open-CMSIS-Pack/cpackget/pull/322), the temporary fix has been removed.
=> cpackget cleanup for version range limitation

pkg/builder/csolution/builder.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1649
List pack needs to be called in quite mode in order not to list info messages
=> Fix: cbuild  reports "bad pack name"

pkg/builder/csolution/builder.go
Addressing: https://github.com/Open-CMSIS-Pack/cbuild/issues/282
Now the output looks like:
```
$ cbuild Hello.csolution.yml -r -p
I: Adding pack "ARM::CMSIS-RTX@5.9.0"
Agreed to embedded license: C:\Users\soumeh01\AppData\Local\Arm\Packs\ARM\CMSIS-RTX\5.9.0\LICENSE
I: Extracting files to C:\Users\soumeh01\AppData\Local\Arm\Packs\ARM\CMSIS-RTX\5.9.0...
```
=> Removed redundant artifact info when packs are missing

pkg/builder/csolution/builder.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1707
The output now looks like :
```
$ cbuild Hello.csolution.yml -r
+----------------------------------------
(1/2) Cleaning context: "Hello.Debug+AVH"
(2/2) Cleaning context: "Hello.Release+AVH"
+----------------------------------------
(1/2) Building context: "Hello.Debug+AVH"
Building CMake target 'Hello.Debug+AVH'
```
=> No separation lines for clean logs

cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, pkg/builder/csolution/builder.go
Addressing partially : https://github.com/Open-CMSIS-Pack/devtools/issues/1700
As part of this PR:
- Removed the `--cbuild2cmake` option.
- Introduced the `--cbuildgen` option.
**Note:** The native CMake-based build approach will now be the default, without requiring an explicit option.
=> Removing cbuild2cmake option and keeping it default option

cmd/cbuild/commands/setup/setup.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1747
Fix cbuild-set location when `--output` is specified - https://github.com/Arm-Debug/devtools-external/pull/1023
=> [cbuild] Restore cbuild setup `--output` option

cmd/cbuild/commands/root.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1756
=> Removing debug information when using --verbose

cmd/cbuild/commands/build/buildcprj.go, cmd/cbuild/commands/list/list_contexts.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, pkg/builder/cproject/builder.go, pkg/builder/cproject/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go
- Addressing https://github.com/Open-CMSIS-Pack/devtools/issues/1777
- Deprecation of `-s` option
- Enabled default schema check
- Added new option to disable schema check `-n,--no-schema-check`
=> Enable default schema check and deprecate -s

cmd/cbuild/commands/build/buildcprj.go, cmd/cbuild/commands/setup/setup.go, pkg/builder/csolution/builder.go
- https://github.com/Open-CMSIS-Pack/devtools/issues/1853
- Renaming the variables aligning with option
- skip schema check on `list packs` when `setup `command is triggered
=> Avoid double schema check on setup command

cmd/cbuild/commands/root.go
- Corrected naming from residual of other changes
=> Correction in naming of option

.github/workflows/test.yml, .golangci.yml, cmd/cbuild/commands/build/buildcprj.go, cmd/cbuild/commands/list/list_contexts.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, pkg/builder/cbuildidx/builder.go, pkg/builder/cproject/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go
- Updated version of linter and migrated configuration to latest
- The new version of linter has megred many tools into one resulted in more checks than before. Hence there are new findings in the code and updates were required for. e.g The linters stylecheck, gosimple, and staticcheck has been merged inside the staticcheck.
- Changes are listed under https://golangci-lint.run/product/migration-guide/
=> Linter updates and configuration migration

pkg/builder/csolution/builder.go, pkg/errutils/errutils.go, pkg/utils/utils.go
- https://github.com/Open-CMSIS-Pack/devtools/issues/2032
As part of this change, missing toolchain registration will result in an error.
```
$ cbuild ./solution.csolution.yml --update-rte -r
warning cbuild: path does not exist: 'tmp'
+--------------------------------------------
(1/4) Cleaning context: "project.AC6+ARMCM55"
warning cbuild: path does not exist: 'out'
(2/4) Cleaning context: "project.GCC+ARMCM55"
warning cbuild: path does not exist: 'out\project\ARMCM55\GCC'
(3/4) Cleaning context: "project.IAR+ARMCM55"
warning cbuild: path does not exist: 'out'
(4/4) Cleaning context: "project.CLANG+ARMCM55"
warning cbuild: path does not exist: 'out'
warning csolution: no compiler registered for 'GCC'. Add path to compiler 'bin' directory with environment variable …
```
=> Irrelevant Error Message When Compiler Registration Variable Is Missing

cmd/cbuild/commands/root.go, cmd/cbuild/commands/root_test.go, cmd/cbuild/commands/setup/setup.go, cmd/cbuild/commands/setup/setup_test.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go, pkg/errutils/errutils.go
- A part of https://github.com/Open-CMSIS-Pack/devtools/issues/2056
- Added `-a, --active` argument to `cbuild root` and `setup` command, which is propagated to csolution
```
Options:
-a, --active arg         Select active target-set: <target-type>[@<set>]
```
=> Extended command line options with -a, --active

cmd/cbuild/commands/list/list.go, cmd/cbuild/commands/list/list_target_sets.go, cmd/cbuild/commands/list/list_target_sets_test.go, pkg/builder/csolution/builder.go
Partly addressing https://github.com/Open-CMSIS-Pack/devtools/issues/2056
- Extended cbuild with `list target-sets` command
=> Added list target-sets command
