Open-CMSIS-Pack/cbuild

cmd/cbuild/root_test.go, pkg/builder/builder.go, pkg/builder/builder_test.go
Reported in https://github.com/Open-CMSIS-Pack/devtools/issues/374
=> Increase log severity when missing packs are reported

README.md, cmd/cbuild/root.go, pkg/builder/builder.go, pkg/builder/builder_test.go
Address https://github.com/Open-CMSIS-Pack/cbuild/issues/13
=> Add `--verbose` flag to enable toolchain's verbose output

README.md, cmd/cbuild/root.go, pkg/builder/builder.go, pkg/builder/builder_test.go
Address issue https://github.com/Open-CMSIS-Pack/cbuild/issues/21
=> Add `--update-rte` flag to enable the update of RTE folder contents

.github/workflows/build.yml, .github/workflows/test.yml
- Added publishing of test results
- Added coverity scan
=> CI enhancements

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/test.yml
UPdated the GH action versions to the latest.
=> Updated GH action versions

go.mod, go.sum
Fixed : [Vulnerability found](https://github.com/Open-CMSIS-Pack/cbuild/actions/runs/4122837823/jobs/7120108449)
=> Updated pkg version to fix vulnerability

cmd/cbuild/commands/list/list.go, cmd/cbuild/commands/list/list_configurations.go, cmd/cbuild/commands/list/list_configurations_test.go, cmd/cbuild/commands/root.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/builder/interface.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Build all configs when no context is provided
=> list configurations command and --configuration option

pkg/builder/csolution/builder.go
Addressing [Issue-51 ](https://github.com/Open-CMSIS-Pack/cbuild/issues/51)
```
info cbuild: Build Invocation  (C) 2023 Arm Ltd. and Contributors
info cbuild: Processing 6 context(s)
<PATH>/Hello2/Hello2.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/Hello2/Hello2.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/Zig/Zig.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/Zig/Zig.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/Hello1/Hello1.Debug+AVH.cprj - info csolution: file generated successfully
<PATH>/Hello1/Hello1.Release+AVH.cprj - info csolution: file generated successfully
<PATH>/Hello2/Hello2.Debug+AVH.cbuild.yml - info csolution: file generated successfully …
```
=> Adding build info in stdout logs

.github/workflows/test.yml
Use GH action to scan for vulnerabilities
=> Use go vuln check action

.github/workflows/test.yml
The separate steps would give detailed results even if the step before gets failed
=> Workflow cleanup

pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go
Address https://github.com/Open-CMSIS-Pack/devtools/issues/1100
=> Clean all selected contexts before rebuilding

.github/workflows/build.yml, .github/workflows/test.yml
As per [documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) _If you define a path with the ! character, you must also define at least one path without the ! character. If you only want to exclude paths, use paths-ignore instead._
=> Use paths-ignore property

.codeclimate.yml, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/data/Test.cbuild-set.yml
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1127
=> Get contexts from *cbuild-set.yml file

.github/dependabot.yaml, .github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/dependency-review.yml, .github/workflows/global.yaml, .github/workflows/markdown.yml, .github/workflows/release.yml, .github/workflows/test.yml, .github/workflows/tpip-check.yml
Addressing : https://github.com/ossf/scorecard/blob/49c0eed3a423f00c872b5c3c9f1bbca9e8aae799/docs/checks.md#token-permissions
=> Added pinned actions and token permissions

pkg/builder/csolution/builder.go
Addressing https://github.com/Open-CMSIS-Pack/devtools/issues/1261
=> Update schema check flag

README.md, cmd/cbuild/commands/root.go, cmd/cbuild/version.go, pkg/builder/csolution/builder.go, pkg/builder/interface.go
Addressing https://github.com/Open-CMSIS-Pack/cbuild/issues/133
=> Extended command line options with --frozen-packs

cmd/cbuild/commands/setup/setup.go, pkg/builder/csolution/builder.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1379
=> Extend setup command to identify compatible layers for reference examples

pkg/builder/csolution/builder.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1381
=> [cbuild] setup command is supposed to pick the first target-type and build-type

cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1415
=> Improved help texts

pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go
Related to https://github.com/Open-CMSIS-Pack/cbuild2cmake/issues/86
=> [cbuild2cmake support] Handle `context-set` flag

.github/workflows/test.yml
=> Update golang linting

pkg/builder/csolution/builder.go, pkg/utils/utils.go
Addressing partially : https://github.com/Open-CMSIS-Pack/devtools/issues/1403
=> Streamline output when using layer detection

cmd/cbuild/commands/list/list_contexts.go, cmd/cbuild/commands/list/list_toolchains.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, go.mod, go.sum, pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/errutils/errutils.go, pkg/utils/utils.go
- Added a check to raise warning and not include `--quite` flag when triggering cbuild2cmake https://github.com/Open-CMSIS-Pack/cbuild/issues/247
- Reenabled support to .yaml extn
=> Added ninja version check

pkg/builder/cbuildidx/builder.go, pkg/builder/cproject/builder.go, pkg/builder/csolution/builder.go, pkg/utils/utils.go
Addressing : https://github.com/Open-CMSIS-Pack/devtools/issues/1586
1. Added clean message for selected contexts on use of `-C, --clean` 
```
+----------------------------------------
(1/2) Cleaning context: "Hello.Debug+AVH"
+------------------------------------------
(2/2) Cleaning context: "Hello.Release+AVH"
+------------------------------------------
```
2. Enabled progress message when cbuild-set file is used.
=> Log cleanup messages on -C

pkg/builder/csolution/builder.go
Addressing : https://github.com/Open-CMSIS-Pack/cbuild/issues/246
=> Forward --cbuild2cmake option when calling csolution convert

cmd/cbuild/commands/build/buildcprj.go, cmd/cbuild/commands/root.go, cmd/cbuild/commands/setup/setup.go, pkg/builder/cbuildidx/builder.go, pkg/builder/cproject/builder.go, pkg/builder/cproject/builder_test.go, pkg/builder/csolution/builder.go, pkg/builder/interface.go, pkg/errutils/errutils.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1593
Also added few debug logs
=> Improved cbuild help text

pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, test/data/Rebuild.cbuild-idx.yml
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1592#issuecomment-2196220276
=> Check if project needs a rebuild

cmd/cbuild/commands/root.go
Addressing: https://github.com/Open-CMSIS-Pack/devtools/issues/1612
=> Updated usage text for '-O'

cmd/cbuild/commands/list/list_toolchains.go
Addressing partially : https://github.com/Open-CMSIS-Pack/devtools/issues/1619
=> Extend list toolchains command options

pkg/builder/cbuildidx/builder.go, pkg/builder/csolution/builder.go
Partly address https://github.com/Open-CMSIS-Pack/devtools/issues/1731
Aligned with https://github.com/Open-CMSIS-Pack/cbuild2cmake/pull/182
=> [cbuild] Replace blanks in CMake target names derived from build contexts

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md
Added Issue/bug templates and contribution guidelines
=> Added Issue templates and Contributing.md

cmd/cbuild/main.go
- https://github.com/Open-CMSIS-Pack/cbuild/issues/344
- Forward csolution return codes for recognizing layer detection and selectable compiler flows
- Align with https://github.com/Arm-Debug/devtools-external/pull/1092
=> Forward return codes for variables and compiler not defined

cmd/cbuild/commands/setup/setup.go, pkg/builder/csolution/builder.go, pkg/builder/csolution/builder_test.go
- https://github.com/Open-CMSIS-Pack/devtools/issues/1889
- Fix regression introduced in https://github.com/Open-CMSIS-Pack/cbuild/pull/343
=> Fix rebuild handling

cmd/cbuild/main.go
- https://github.com/Open-CMSIS-Pack/cbuild/issues/344
- Complementary to https://github.com/Open-CMSIS-Pack/cbuild/pull/345
=> Improve exit error handling

pkg/builder/cbuildidx/builder.go, pkg/utils/utils.go, pkg/utils/utils_test.go
- https://github.com/Open-CMSIS-Pack/cmsis-toolbox/issues/219
- This change adds a message in the build messages listing toolchain used to build
- The change will only be reflected with cbuild2cmake use
- The example output shall look like below example
```
$ cbuild ./Hello.csolution.yml -r
+------------------------------------------
(1/2) Cleaning context: "Hello.Debug+CS300"
(2/2) Cleaning context: "Hello.Release+CS300"
+------------------------------------------
(1/2) Building context: "Hello.Debug+CS300"
Using AC6 V6.22.0 compiler, from: 'C:/tools/ArmCompilerforEmbedded6.22/bin'
Building CMake target 'Hello.Debug+CS300'
...
...
+--------------------------------------------
(2/2) Building context: "Hello.Release+CS300"
Using GCC V10.3.1 compiler, from: 'C:/Program Files (x86)/Arm GNU …
```
=> Show toolchain used for the build process

.github/workflows/markdown.yml
-Improved markdown link checker
=> Improved md link checker

.github/pull_request_template.md
- Fixed and removed duplicate checks
=> Removed duplicate checks

cmd/cbuild/commands/root.go
- Addressing part of https://github.com/Open-CMSIS-Pack/devtools/issues/1917
=> Changed help text for option --output

cmd/cbuild/commands/root.go
-Updated default value for --output option 
- https://github.com/Open-CMSIS-Pack/devtools/issues/1917
=> Updated default value for --output option

cmd/cbuild/version.go
=> Updated copyright with current year

.github/dependabot.yaml
This update introduces minor adjustments to the Dependabot strategy:  
- **Consolidation of Minor and Patch Updates**: Minor and patch updates will now be merged into a single PR, reducing the overall number of PRs created.  
- **Separate PRs for Security and Major Updates**: Security and major version updates are critical and require dedicated attention. These will be handled in separate PRs to ensure a more focused review.
- PR shall be assigned to a direct reviewer.
=> Update dependabot scan strategy

cmd/cbuild/commands/list/list.go, cmd/cbuild/commands/list/list_contexts.go, cmd/cbuild/commands/list/list_toolchains.go
- Updated short help texts
- [NA] 🤖 This change is covered by unit tests (if applicable).
- [NA] 🛡️ Security impacts have been considered (if relevant).
- [NA] 📖 Documentation updates are complete (if required).
- [NA] 🧠 Third-party dependencies and TPIP updated (if required).
=> Updated short help text for consistency

pkg/builder/csolution/builder.go, pkg/utils/utils.go, pkg/utils/utils_test.go
=> Cleanup doesn't remove *.cbuild.yml file

.github/workflows/test.yml
=> use pinned runner images

pkg/builder/cbuildidx/builder.go, pkg/builder/cbuildidx/builder_test.go, pkg/utils/utils.go, pkg/utils/west.go, pkg/utils/west_test.go, test/data/west.Debug+CM0.cbuild.yml, test/data/west.cbuild-idx.yml
- Partly address https://github.com/Open-CMSIS-Pack/devtools/issues/2211
-
=> [cbuild] Initial zephyr/west integration support
